fieldLayouts:
  ca8c8850-a918-40e5-8764-6c41ff22005c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1b30d64f-2b47-47ab-b74c-56ca223018fd # Redirect URL
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ad29506d-5bf0-4507-ace0-445d37ad4df3 # Hide from navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06536257-6591-4559-b58a-811c65d68b07 # Hide from search
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b8cad5cb-060a-4f09-b35c-c4ddd40c147b # Teaser title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8faa7537-f8f6-4808-88f5-909c50cf87b8 # Teaser text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6535d548-8ab4-4b6f-acef-a044ef5e2f97 # Teaser image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: redirect
hasTitleField: true
name: Redirect
section: ed9d3647-71e9-4ce1-a143-0a5692fd03d0 # Pages
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
