fieldLayouts:
  32cc6c1a-7f08-463a-9c82-c51dbeee59c0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogs
name: Blogs
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # Botanic Gardens of South Australia
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 01307701-e168-4e52-b801-31b6d46e1dba
