dateModified: 1575351667
email:
  fromEmail: dew.internet@sa.gov.au
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  703d4722-e4f4-477c-b2d6-0a3bbbc75d06:
    name: Errors
  9cd50e65-29bd-4d2e-a248-a71356160704:
    name: Common
fields:
  5a7e45ac-5320-4994-b609-701df93fd4df:
    name: 'Error text'
    handle: errorText
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
  6cf7c061-7452-488b-8cdb-6da1270cbebb:
    name: 'Error image'
    handle: errorImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
  9926cd8c-3c23-4db7-b642-71915fc75d9e:
    name: 'Error headline'
    handle: errorHeadline
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.7
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  06b0ecd6-27c0-49bb-9c3d-d8ef8b180648:
    name: Errors
    handle: errors
    type: channel
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
        enabledByDefault: true
        hasUrls: false
        uriFormat: ''
        template: null
    entryTypes:
      d46f4275-d7f2-42a8-a6dd-37a05635f7b6:
        name: Errors
        handle: errors
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          bc4438f1-97f6-4fb5-aa7d-3adbdec9e4bb:
            tabs:
              -
                name: Errors
                sortOrder: 1
                fields:
                  5a7e45ac-5320-4994-b609-701df93fd4df:
                    required: false
                    sortOrder: 3
                  6cf7c061-7452-488b-8cdb-6da1270cbebb:
                    required: false
                    sortOrder: 2
                  9926cd8c-3c23-4db7-b642-71915fc75d9e:
                    required: false
                    sortOrder: 1
  520f2a2f-1aa1-4cd1-b834-75ffd25c78be:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index
    entryTypes:
      f233e7e9-6504-4a61-814d-653fa51b42ac:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  270800a7-8281-47bc-b872-3306d72b5e85:
    name: $SITE_NAME
sites:
  c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
    name: $SITE_NAME
    handle: default
    language: en-GB
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
    siteGroup: 270800a7-8281-47bc-b872-3306d72b5e85
system:
  edition: pro
  name: $SITE_NAME
  live: true
  schemaVersion: 3.3.3
  timeZone: Australia/Adelaide
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  0c19a425-0d80-42f5-a12b-77da139b7443:
    name: Site
    handle: site
    type: craft\volumes\Local
    hasUrls: true
    url: '@assetsUrl/images/site'
    settings:
      path: '@webroot/dist/images/site'
    sortOrder: 1
