dateModified: 1576215082
email:
  fromEmail: dew.internet@sa.gov.au
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  703d4722-e4f4-477c-b2d6-0a3bbbc75d06:
    name: Errors
  9cd50e65-29bd-4d2e-a248-a71356160704:
    name: Common
fields:
  55e4bb22-e961-4c2c-a523-3e4e473c1abc:
    name: 'Nav title'
    handle: navTitle
    instructions: 'Alternate title for navigation menus'
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 9cd50e65-29bd-4d2e-a248-a71356160704
  5a7e45ac-5320-4994-b609-701df93fd4df:
    name: 'Error text'
    handle: errorText
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
  6cf7c061-7452-488b-8cdb-6da1270cbebb:
    name: 'Error image'
    handle: errorImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: ''
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: ''
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
  8517d244-bfd4-4833-8e6f-61e298de4fe0:
    name: 'Content builder'
    handle: contentBuilder
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_contentbuilder}}'
      propagationMethod: all
    contentColumnType: string
    fieldGroup: 9cd50e65-29bd-4d2e-a248-a71356160704
  92cac0fb-77b5-4d78-ac2d-642a12e260d6:
    name: 'Nav image'
    handle: navImage
    instructions: 'Alternate image for navigation menus'
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:0c19a425-0d80-42f5-a12b-77da139b7443'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:0c19a425-0d80-42f5-a12b-77da139b7443'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: 9cd50e65-29bd-4d2e-a248-a71356160704
  9926cd8c-3c23-4db7-b642-71915fc75d9e:
    name: 'Error headline'
    handle: errorHeadline
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 703d4722-e4f4-477c-b2d6-0a3bbbc75d06
matrixBlockTypes:
  6cd6a957-fbf1-4f55-9ea5-336c24c4cff1:
    field: 8517d244-bfd4-4833-8e6f-61e298de4fe0
    name: Image
    handle: image
    sortOrder: 2
    fields:
      0c20333d-9ca4-43fa-a8bf-120cb9a1841d:
        name: Image
        handle: image
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
      cbe8d5e6-8f7c-4ccd-bff2-03025a8f4ab2:
        name: Caption
        handle: caption
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      3907fc0c-fab3-4406-a2f8-b58e6cb501a8:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              0c20333d-9ca4-43fa-a8bf-120cb9a1841d:
                required: true
                sortOrder: 1
              cbe8d5e6-8f7c-4ccd-bff2-03025a8f4ab2:
                required: false
                sortOrder: 2
  9f0c057e-dae9-4c04-828e-a529b49fdd8f:
    field: 8517d244-bfd4-4833-8e6f-61e298de4fe0
    name: 'Breakout box'
    handle: breakoutBox
    sortOrder: 3
    fields:
      db025c9e-e19f-4d13-a006-5290312c4d46:
        name: 'Content body'
        handle: contentBody
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: '1'
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      d6506bf3-0647-4dd0-92f1-6748729245e5:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              db025c9e-e19f-4d13-a006-5290312c4d46:
                required: true
                sortOrder: 1
  c2246b81-a258-4197-81b2-052471509f7e:
    field: 8517d244-bfd4-4833-8e6f-61e298de4fe0
    name: Text
    handle: text
    sortOrder: 1
    fields:
      583cf726-dc0e-4600-880b-60ef4cbb99a4:
        name: 'Body copy'
        handle: bodyCopy
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\redactor\Field
        settings:
          redactorConfig: Simple.json
          purifierConfig: ''
          cleanupHtml: true
          removeInlineStyles: '1'
          removeEmptyTags: '1'
          removeNbsp: '1'
          purifyHtml: '1'
          columnType: text
          availableVolumes: '*'
          availableTransforms: '*'
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      6c72a524-c0e5-4e53-a309-dde9dd740274:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              583cf726-dc0e-4600-880b-60ef4cbb99a4:
                required: true
                sortOrder: 1
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.7
    settings:
      pluginName: Retour
      createUriChangeRedirects: true
      uriChangeRedirectSrcMatch: pathonly
      alwaysStripQueryString: false
      preserveQueryString: false
      recordRemoteIp: true
      staticRedirectDisplayLimit: 100
      dynamicRedirectDisplayLimit: 100
      stripQueryStringFromStats: true
      statsStoredLimit: 1000
      refreshIntervalSecs: 5
      automaticallyTrimStatistics: '1'
      statisticsRateLimitMs: '3600000'
      statsDisplayLimit: 1000
      excludePatterns:
        -
          pattern: '/cpresources/.*'
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  route-map:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  06b0ecd6-27c0-49bb-9c3d-d8ef8b180648:
    name: Errors
    handle: errors
    type: channel
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
        enabledByDefault: true
        hasUrls: false
        uriFormat: ''
        template: null
    entryTypes:
      d46f4275-d7f2-42a8-a6dd-37a05635f7b6:
        name: Errors
        handle: errors
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          bc4438f1-97f6-4fb5-aa7d-3adbdec9e4bb:
            tabs:
              -
                name: Errors
                sortOrder: 1
                fields:
                  5a7e45ac-5320-4994-b609-701df93fd4df:
                    required: false
                    sortOrder: 3
                  6cf7c061-7452-488b-8cdb-6da1270cbebb:
                    required: false
                    sortOrder: 2
                  9926cd8c-3c23-4db7-b642-71915fc75d9e:
                    required: false
                    sortOrder: 1
  520f2a2f-1aa1-4cd1-b834-75ffd25c78be:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index
    entryTypes:
      f233e7e9-6504-4a61-814d-653fa51b42ac:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  270800a7-8281-47bc-b872-3306d72b5e85:
    name: $SITE_NAME
sites:
  c9d15c14-6670-4c26-a9b8-5ea0cebb6354:
    siteGroup: 270800a7-8281-47bc-b872-3306d72b5e85
    name: $SITE_NAME
    handle: default
    language: en-GB
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: pro
  name: $SITE_NAME
  live: true
  schemaVersion: 3.3.3
  timeZone: Australia/Adelaide
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  0c19a425-0d80-42f5-a12b-77da139b7443:
    name: Site
    handle: site
    type: craft\volumes\Local
    hasUrls: true
    url: '@assetsUrl/images/site'
    settings:
      path: '@webroot/dist/images/site'
    sortOrder: 1
