childBlocks: ''
field: fa112548-c36b-46b2-901a-839be3825ce8 # Content builder
fieldLayouts:
  df57a376-0478-4a36-883e-641cfa052146:
    tabs:
      -
        elements:
          -
            fieldUid: 6cbd429a-eb7f-435a-a392-ac75de54825e # Block title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: accordion
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Accordion
sortOrder: 5
topLevel: true
