childBlocks: ''
field: fa112548-c36b-46b2-901a-839be3825ce8 # Content builder
fieldLayouts:
  71d0976d-064e-452e-b433-04fdf2585b09:
    tabs:
      -
        elements:
          -
            fieldUid: 6cbd429a-eb7f-435a-a392-ac75de54825e # Block title
            instructions: ''
            label: Heading
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6588c8f-8fbb-4942-bc54-baf1b82001da # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: form
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Form
sortOrder: 5
topLevel: true
