childBlocks: ''
field: 8cd0bce8-3671-4772-9479-7c23c0d5948c # Image gallery
fieldLayouts:
  c138d949-bbd9-4657-a30f-ab0c969bc2d3:
    tabs:
      -
        elements:
          -
            fieldUid: c1fbbe64-a078-4af6-9266-3321a7dc4724 # Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 112c70eb-196d-49cf-8c69-cb6cd11432ac # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: imageItem
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Image
sortOrder: 1
topLevel: true
