fieldLayouts:
  f5363b55-b061-491a-9d18-f7acdb6b2de4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: sharedDocuments
hasUrls: true
name: 'Shared documents'
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: $CLOUDFRONT_PATH_PREFIX
  expires: '12 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: shared/docs/
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
