contentColumnType: string
fieldGroup: 820d67ae-c658-4d30-8347-14058c97e1c1 # Globals
handle: acknowledgementImage
instructions: ''
name: 'Acknowledgement image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:35b5ffbd-9878-4e66-8a46-11adf9162b06' # Shared images
  singleUploadLocationSubpath: AOC
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
