contentColumnType: string
fieldGroup: 5530f693-5e22-48f0-ba53-d8e8999ec908 # Common
handle: contentBuilder
instructions: ''
name: 'Content builder'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
