contentColumnType: string
fieldGroup: 5530f693-5e22-48f0-ba53-d8e8999ec908 # Common
handle: ctas
instructions: ''
name: CTAs
searchable: false
settings:
  contentTable: '{{%matrixcontent_ctas}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
