contentColumnType: string
fieldGroup: 7cc23e51-bc00-4d62-832b-6cc9c0b4d923 # Errors
handle: errorImage
instructions: ''
name: 'Error image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
