contentColumnType: string
fieldGroup: 5530f693-5e22-48f0-ba53-d8e8999ec908 # Common
handle: heroBanner
instructions: ''
name: 'Hero banner'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6b51a275-7999-4ae0-bbde-0f0c7a4aad5c' # Site documents
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8' # Site images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
