contentColumnType: boolean
fieldGroup: 7bfcbb3d-29bf-40e4-a9a8-838a0ebf268b # Settings
handle: hideSearch
instructions: 'Hide this page from site search results'
name: 'Hide from search'
searchable: false
settings:
  default: false
  offLabel: Show
  onLabel: Hide
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
