contentColumnType: text
fieldGroup: 5530f693-5e22-48f0-ba53-d8e8999ec908 # Common
handle: label
instructions: ''
name: Label
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
