contentColumnType: boolean
fieldGroup: 7bfcbb3d-29bf-40e4-a9a8-838a0ebf268b # Settings
handle: showCaption
instructions: 'Show image caption'
name: 'Show caption'
searchable: false
settings:
  default: false
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
