contentColumnType: datetime
fieldGroup: 5530f693-5e22-48f0-ba53-d8e8999ec908 # Common
handle: startDate
instructions: ''
name: 'Start date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '15'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
