contentColumnType: string
fieldGroup: 7bfcbb3d-29bf-40e4-a9a8-838a0ebf268b # Settings
handle: teaserImage
instructions: 'Alternate image for navigation menus etc.'
name: 'Teaser image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:6b51a275-7999-4ae0-bbde-0f0c7a4aad5c'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6b51a275-7999-4ae0-bbde-0f0c7a4aad5c'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e06bad3e-e63c-49ac-b605-164d334f58f8'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
