dateModified: 1621928391
email:
  fromEmail: dew.internet@sa.gov.au
  fromName: 'Craft Bot 🤖 '
  replyToEmail: dew.internet@sa.gov.au
  template: mail/_entry
  transportSettings:
    encryptionMethod: tls
    host: $EMAIL_SMTP_HOST_NAME
    password: $EMAIL_SMTP_PASSWORD
    port: $EMAIL_SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
plugins:
  activeusers:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.3.0
  hide-admin:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 98VD4QK7Z71771L8U1NE7WVO
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
                -
                  - unsharpMask
                  - '20'
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $IMAGE_HANDLER_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: true
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  incognito-field:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  lockout:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: OAL9GD6HGCZSLCZGB3V1DA1Y
    schemaVersion: 2.8.16
  publisher:
    edition: standard
    enabled: true
    schemaVersion: 2.0.6
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-anchors:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  retour:
    edition: standard
    enabled: true
    licenseKey: KUH6PJFJKHHVLO280GSIAUF8
    schemaVersion: 3.0.9
  seomatic:
    edition: standard
    enabled: true
    licenseKey: ZPLAAH9FG7R6D3CT6YSIHSKW
    schemaVersion: 3.0.9
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: craft3
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Australia/Adelaide
