fieldLayouts:
  f17eb96b-6f58-4b4e-9d9c-29b22a3c382f:
    tabs:
      -
        elements:
          -
            fieldUid: 38aeb4dd-0882-41f8-98a5-bf78e31d659a # Site logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eba7d0a3-19f3-4d50-8ea8-850b84c5af55 # Favicon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: site
name: Site
