enableVersioning: true
handle: blog
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # Botanic Gardens of South Australia
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry
    uriFormat: 'blogs/{slug}'
type: channel
