enableVersioning: false
handle: errors
name: Errors
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # Botanic Gardens of South Australia
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: null
type: channel
