enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # craft3
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
