enableVersioning: false
handle: notFound
name: '404 Not Found'
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # craft3
    enabledByDefault: true
    hasUrls: true
    template: 404.twig
    uriFormat: '404'
type: single
