enableVersioning: false
handle: serviceUnavailable
name: '503 Service Unavailable'
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # craft3
    enabledByDefault: true
    hasUrls: true
    template: 503.twig
    uriFormat: '503'
type: single
