enableVersioning: false
handle: siteOffline
name: 'Site Offline'
propagationMethod: all
siteSettings:
  7aa2b387-b891-449b-bbbb-b709fb95595e: # craft3
    enabledByDefault: true
    hasUrls: true
    template: offline.twig
    uriFormat: offline
type: single
